### ISSUE TITLE
A few bits I noticed in 72a56a7 (clean code + perf)

### ISSUE THREAD

**Issue by Evrey** [Kixiron/lasso#1]
https://github.com/Kixiron/lasso/tree/72a56a76564493d7e191bb46b0f53034452ecd99

- Arena allocator for the strings to fragment heap memory less?
  - Capacity would then relate to spare bytes in the current arena allocator chunk.
  - You could use the `typed-arena` crate. Has good code.
- `NonZeroUsize::new(int + 1).unwrap_or_else(|| {` can just be a `new_unchecked` call.
- You can blanket-implement `from_usize` for all `Key`s by just `expect`ing `try_from_usize`.

Other than that code's lookin' good. °^°b

**Comment by Kixiron** [comment]
Got everything rounded out!
