### ISSUE TITLE
impl Index<Key> for Rodeo

### ISSUE THREAD

**Issue by 1011X** [Kixiron/lasso#10]
Indexing an interner by key seems very convenient. Unfortunately none of the `Rodeo` family of types currently allow for that. I propose that for each of the `Rodeo` types:
1. `rodeo[key]` replace the behavior of `rodeo.resolve(key)`,
2. `rodeo.resolve(key)` replace the behavior of `rodeo.try_resolve(key)`,
3. `rodeo.try_resolve()` be deprecated.

Obviously (2) will result in an API breaking change. This shouldn't be an issue since `lasso` is still pre-`v1.0.0`, but if avoiding this is desired, there are other options. In addition to (1), we could:
+ leave `.try_resolve()` and deprecate `.resolve()` (unnecessarily wordy; inconsistent naming),
+ leave both `.try_resolve()` and `.resolve()` (there's now more than one way of doing something).

I'm not completely happy with either of these alternative solutions, but then again, I don't even use `lasso` (*yet*) so perhaps consideration should be placed on its users rather than my API preferences.

**Comment by Kixiron** [comment]
Good idea on implementing `Index`, but I'm not entirely convinced that `.try_resolve()` needs to be removed. From what I've seen, the vast majority of users prefer `.resolve()` (which would become indexing), so this would break most current users for not a whole lot of gain. I'm alright with having `Index` be syntactic sugar for `.resolve()`, that's a nice convenience shortcut
