### ISSUE TITLE
Possible race condition in ThreadedRodeo

### ISSUE THREAD

**Issue by shadowislord** [Kixiron/lasso#18]
Hi,

Really appreciate this great library! I've encountered a small issue, which I believe could be a race condition in ThreadedRodeo.

It is located in https://github.com/Kixiron/lasso/blob/master/src/multi_threaded.rs#L341-L342

```rust
self.map.insert(string, key);
self.strings.insert(key, string);
```

Suppose a new string is being interned by two threads running at the same time, then the if at [line 331](https://github.com/Kixiron/lasso/blob/master/src/multi_threaded.rs#L331) (`shard.read().get(...)`) would return `None` for both threads. Both threads continue to line 341, one will call `self.map.insert()` which will write the string into the map, the second thread would do the same, overwriting the value from the first thread.

This would then create a situation where two Spurs could exist that resolve to identical strings, but not be equal to each other because their keys are different.

One option to address this would be to lock the shard for the duration as we insert into the arena and increment the key. If we would like to avoid locking for that long, perhaps checking the return value from `self.map.insert(...)` would help, as we can verify that we already added that string in, and just return its key, but then we would need to undo the other operations, and it doesn't seem possible to remove strings from the arena. This way we may end up using slightly more memory and keys than actually needed (which is already the case in this scenario), but at the very least, the Spur equality property would be maintained.

**Comment by Kixiron** [comment]
Thank you for the issue, I really want to apologize for the slow response time since I've been really busy lately, I'm terribly sorry.
Locking the shards sounds like a good strategy and you're correct in the analysis that strings cannot be removed. As this is a degenerate case I do want to be careful not to affect the fast path of getting an already-interned string since that's the path most traveled. I'll try to get around to this in the next week or so, but if you're willing to make a PR I'd happily accept it

**Comment by Kixiron** [comment]
Do you think replacing the lines you mentioned with
```rust
if let Some(key) = self.map.insert(string, key) {
    return Ok(key);
}
self.strings.insert(key, string);
```
would fix this?

**Comment by shadowislord** [comment]
I looked into this a bit, and actually `self.map.insert(...)` has a problem, because it will still overwrite the key that was there, whereas we only want to conditionally insert the key if it's not there. Hence a situation where `get_or_intern()` would return different spurs for the same string can still exist. 

I modified one of the existing tests, and I can get it to fail 99% of the time when running in debug on current master:
```rust
#[test]
#[cfg(not(any(miri, feature = "no-std")))]
fn get_or_intern_threaded() {
    const THREADS: usize = 10;

    let mut handles = Vec::with_capacity(THREADS);
    let barrier = Arc::new(Barrier::new(THREADS));
    let rodeo = Arc::new(ThreadedRodeo::default());
    let expected = Spur::try_from_usize(0).unwrap();

    for _ in 0..THREADS {
        let moved_rodeo = Arc::clone(&rodeo);
        let moved_barrier = Arc::clone(&barrier);
        handles.push(thread::spawn(move || {
            moved_barrier.wait();
            assert_eq!(expected, moved_rodeo.get_or_intern("A"));
            assert_eq!(expected, moved_rodeo.get_or_intern("A"));
            assert_eq!(expected, moved_rodeo.get_or_intern("A"));
            assert_eq!(expected, moved_rodeo.get_or_intern("A"));
        }));
    }

    for handle in handles {
        handle.join().unwrap();
    }
}
```

I was able to fix it by modifying the body of try_get_or_intern like so:
```rust
pub fn try_get_or_intern<T>(&self, val: T) -> LassoResult<K>
where
    T: AsRef<str>,
{
    let string_slice = val.as_ref();

    if let Some(key) = self.map.get(string_slice) {
        Ok(*key)
    } else {
        // Safety: The drop impl removes all references before the arena is dropped
        let string: &'static str =
            unsafe { self.arena.lock().unwrap().store_str(string_slice)? };

        let make_new_key = || {
            K::try_from_usize(self.key.fetch_add(1, Ordering::SeqCst))
                .ok_or_else(|| LassoError::new(LassoErrorKind::KeySpaceExhaustion))
        };

        let key = *self.map.entry(string).or_try_insert_with(make_new_key)?.value();
        self.strings.insert(key, string);
        Ok(key)
    }
}
```

I removed the locking of the shard in the else case. I wasn't sure exactly if it was adding any value since we already did a `self.map.get(...)` before which returned None.

Next, I moved the key generation code into a closure which is only called if the string wasn't in the map already. 

Using this version of the method makes the test pass, however we may end up leaking a bit of memory in the edge case situation.

**Comment by Kixiron** [comment]
I pushed this to master (along with a similar fix for `.get_or_intern_static()`) and I can't get it to race locally, can you?

**Comment by shadowislord** [comment]
Yep, seems to be working well now. Tests are passing for me. Thanks!
