### ISSUE TITLE
`raw_entry_mut` to speed up `try_get_or_intern`?

### ISSUE THREAD

**Issue by Evrey** [Kixiron/lasso#2]
To my knowledge `dashmap` can't do dat, but on nightly `std`'s hash map and `hashbrown` on stable can. What this allows you to do is performing a single hash map look-up, no matter whether the input is already interned or needs to be stored.

The big downside is more complicated code, especially with some feature `cfg`s for nightly, and, well, this only being an optimisation for the ST interner. So all this may be considered »not worth it«.

**Comment by Kixiron** [comment]
I'll look into it today, it may be worth investigating

**Comment by Kixiron** [comment]
I’ve implemented this, it’s available by default when the `hashbrown-table` feature is enabled and is available optionally for nightly users under the `nightly` feature
