### ISSUE TITLE
Files with spaces break bazel

### ISSUE THREAD

**Issue by cristifalcas** [Kixiron/lasso#28]
Hello,

There are 2 files that spaces in the name: `Before Release.md`, and  `To Do.md`.

Those 2 break rust bazel projects that use lasso.

Will you consider a PR to fix this?

**Comment by Kixiron** [comment]
Fixed, this seems like something that upstream bazel needs to fix though

**Comment by cristifalcas** [comment]
Thank you!
They do have a issue for this: https://github.com/bazelbuild/bazel/issues/4327
